version: '3.5'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dummy

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"